from PIL import Image, TiffImagePlugin
import os

# Make sure the ./tmp/ directory exists
os.makedirs('./tmp/', exist_ok=True)

# Create a simple image using PIL
image = Image.new('RGB', (100, 100), color='blue')

# Define metadata using TIFF tag numbers
metadata = {
    270: "A blue square",  # ImageDescription
    282: (96, 1),  # XResolution
    283: (96, 1),  # YResolution
    296: 2,  # ResolutionUnit, 2 signifies inches
    305: "Python PIL",  # Software
    33432: "Copyright 2023",  # Copyright
    315: "Generated by PIL"  # Artist
}

# Use the save method's additional parameters to add metadata
tif_info = TiffImagePlugin.ImageFileDirectory_v2()

for tag, value in metadata.items():
    tif_info[tag] = value

# Save the image with metadata
image.save('./tmp/generated_image_with_metadata.tif', tiffinfo=tif_info)
print("TIFF image with metadata saved successfully.")