import os

# Define the content of the mif file
mif_content = """
<MIFFile 6.0>
<CharacterMapping <<
<Name (DefaultParagraphFont <Minion Pro><R=0,G=0,B=0>) <MacPSRoman> >>
>>
<DefaultFont <Minion Pro>>
<VariableFont <Minion Pro>>
<DefaultColor <BlackColor>>
<DefaultSwatch <NoColorSwatch>>
<DefaultTable <NoTable>>
<DefaultTextFrame <NoTextFrame>>
<DefaultPage <NoPage>>
<DefaultMasterPage <NoMasterPage>>
<DefaultReferencePage <NoReferencePage>>
<DefaultLayer <NoLayer>>
<DefaultConditionalTextTag <NoConditionalTextTag>>
<DefaultCondition <NoCondition>>
<DefaultTableColumn <NoTableColumn>>
<DefaultTableRow <NoTableRow>>
<DefaultInsertionPoint <NoInsertionPoint>>
<DefaultTextLine <NoTextLine>>
<DefaultTextColumn <NoTextColumn>>
<DefaultText <NoText>>
<DefaultPosition <NoPosition>>
<DefaultAnchor <NoAnchor>>
<DefaultMarker <NoMarker>>
<DefaultObject <NoObject>>
<DefaultFrame <NoFrame>>
<DefaultGraphic <NoGraphic>>
<DefaultTable <NoTable>>
<DefaultCell <NoCell>>
<DefaultRow <NoRow>>
<DefaultColumn <NoColumn>>
<DefaultImage <NoImage>>
<DefaultImport <NoImport>>
<DefaultLink <NoLink>>
<DefaultCondition <NoCondition>>
<DefaultXMLElement <NoXMLElement>>
<DefaultXMLAttribute <NoXMLAttribute>>
<DefaultTextVariableInstance <NoTextVariableInstance>>
<DefaultCrossReferenceFormat <NoCrossReferenceFormat>>
<DefaultIndexFormat <NoIndexFormat>>
<DefaultParagraphStyle <NoParagraphStyle>>
<DefaultCharacterStyle <NoCharacterStyle>>
<DefaultTableStyle <NoTableStyle>>
<DefaultCellStyle <NoCellStyle>>
<DefaultObjectStyle <NoObjectStyle>>
<DefaultRootStyle <NoRootStyle>>
<DefaultConditionalTextTag <NoConditionalTextTag>>
<DefaultVariable <NoVariable>>
<DefaultXMLComment <NoXMLComment>>
<DefaultXMLElement <NoXMLElement>>
<DefaultXMLElementType <NoXMLElementType>>
<DefaultSVVariable <NoSVVariable>>
<DefaultSVVariableInstance <NoSVVariableInstance>>
<DefaultChange <NoChange>>
<DefaultChangeList <NoChangeList>>
<DefaultChangePage <NoChangePage>>
<DefaultChangeColumn <NoChangeColumn>>
<DefaultChangeRow <NoChangeRow>>
<DefaultChangeCell <NoChangeCell>>
<DefaultChangeLine <NoChangeLine>>
<DefaultChangeText <NoChangeText>>
<DefaultChangeFrame <NoChangeFrame>>
<DefaultChangeGraphic <NoChangeGraphic>>
<DefaultChangeMarker <NoChangeMarker>>
<DefaultChangeImage <NoChangeImage>>
<DefaultChangeCondition <NoChangeCondition>>
<DefaultChangeTable <NoChangeTable>>
<DefaultChangeObject <NoChangeObject>>
<DefaultChangeXMLElement <NoChangeXMLElement>>
<DefaultChangeXMLElementType <NoChangeXMLElementType>>
<DefaultChangeTextVariableInstance <NoChangeTextVariableInstance>>
<DefaultChangeCrossReferenceFormat <NoChangeCrossReferenceFormat>>
<DefaultChangeIndexFormat <NoChangeIndexFormat>>
<DefaultChangeParagraphStyle <NoChangeParagraphStyle>>
<DefaultChangeCharacterStyle <NoChangeCharacterStyle>>
<DefaultChangeTableStyle <NoChangeTableStyle>>
<DefaultChangeCellStyle <NoChangeCellStyle>>
<DefaultChangeObjectStyle <NoChangeObjectStyle>>
<DefaultChangeRootStyle <NoChangeRootStyle>>
<DefaultChangeConditionalTextTag <NoChangeConditionalTextTag>>
<DefaultChangeVariable <NoChangeVariable>>
<DefaultChangeXMLComment <NoChangeXMLComment>>
<DefaultChangeXMLElement <NoChangeXMLElement>>
<DefaultChangeSVVariable <NoChangeSVVariable>>
<DefaultChangeSVVariableInstance <NoChangeSVVariableInstance>>
<DefaultChangeCondition <NoChangeCondition>>
<DefaultChange <NoChange>>
<DefaultChangeList <NoChangeList>>
<DefaultChangePage <NoChangePage>>
<DefaultChangeColumn <NoChangeColumn>>
<DefaultChangeRow <NoChangeRow>>
<DefaultChangeCell <NoChangeCell>>
<DefaultChangeLine <NoChangeLine>>
<DefaultChangeText <NoChangeText>>
<DefaultChangeFrame <NoChangeFrame>>
<DefaultChangeGraphic <NoChangeGraphic>>
<DefaultChangeMarker <NoChangeMarker>>
<DefaultChangeImage <NoChangeImage>>
<DefaultChangeXMLElement <NoChangeXMLElement>>
<DefaultChangeXMLElementType <NoChangeXMLElementType>>
<DefaultChangeTextVariableInstance <NoChangeTextVariableInstance>>
<DefaultChangeCrossReferenceFormat <NoChangeCrossReferenceFormat>>
<DefaultChangeIndexFormat <NoChangeIndexFormat>>
<DefaultChangeParagraphStyle <NoChangeParagraphStyle>>
<DefaultChangeCharacterStyle <NoChangeCharacterStyle>>
<DefaultChangeTableStyle <NoChangeTableStyle>>
<DefaultChangeCellStyle <NoChangeCellStyle>>
<DefaultChangeObjectStyle <NoChangeObjectStyle>>
<DefaultChangeRootStyle <NoChangeRootStyle>>
<DefaultChangeConditionalTextTag <NoChangeConditionalTextTag>>
<DefaultChangeVariable <NoChangeVariable>>
<DefaultChangeXMLComment <NoChangeXMLComment>>
<DefaultChangeXMLElement <NoChangeXMLElement>>
<DefaultChangeSVVariable <NoChangeSVVariable>>
<DefaultChangeSVVariableInstance <NoChangeSVVariableInstance>>
<DefaultChangeCondition <NoChangeCondition>>
<DefaultChange <NoChange>>
<DefaultChangeList <NoChangeList>>
<DefaultChangePage <NoChangePage>>
<DefaultChangeColumn <NoChangeColumn>>
<DefaultChangeRow <NoChangeRow>>
<DefaultChangeCell <NoChangeCell>>
<DefaultChangeLine <NoChangeLine>>
<DefaultChangeText <NoChangeText>>
<DefaultChangeFrame <NoChangeFrame>>
<DefaultChangeGraphic <NoChangeGraphic>>
<DefaultChangeMarker <NoChangeMarker>>
<DefaultChangeImage <NoChangeImage>>
<DefaultChangeXMLElement <NoChangeXMLElement>>
<DefaultChangeXMLElementType <NoChangeXMLElementType>>
<DefaultChangeTextVariableInstance <NoChangeTextVariableInstance>>
<DefaultChangeCrossReferenceFormat <NoChangeCrossReferenceFormat>>
<DefaultChangeIndexFormat <NoChangeIndexFormat>>
<DefaultChangeParagraphStyle <NoChangeParagraphStyle>>
<DefaultChangeCharacterStyle <NoChangeCharacterStyle>>
<DefaultChangeTableStyle <NoChangeTableStyle>>
<DefaultChangeCellStyle <NoChangeCellStyle>>
<DefaultChangeObjectStyle <NoChangeObjectStyle>>
<DefaultChangeRootStyle <NoChangeRootStyle>>
<DefaultChangeConditionalTextTag <NoChangeConditionalTextTag>>
<DefaultChangeVariable <NoChangeVariable>>
<DefaultChangeXMLComment <NoChangeXMLComment>>
<DefaultChangeXMLElement <NoChangeXMLElement>>
<DefaultChangeSVVariable <NoChangeSVVariable>>
<DefaultChangeSVVariableInstance <NoChangeSVVariableInstance>>
<DefaultChangeCondition <NoChangeCondition>>
<DefaultChange <NoChange>>
<DefaultChangeList <NoChangeList>>
<DefaultChangePage <NoChangePage>>
<DefaultChangeColumn <NoChangeColumn>>
<DefaultChangeRow <NoChangeRow>>
<DefaultChangeCell <NoChangeCell>>
<DefaultChangeLine <NoChangeLine>>
<DefaultChangeText <NoChangeText>>
<DefaultChangeFrame <NoChangeFrame>>
<DefaultChangeGraphic <NoChangeGraphic>>
<DefaultChangeMarker <NoChangeMarker>>
<DefaultChangeImage <NoChangeImage>>
<DefaultChangeXMLElement <NoChangeXMLElement>>
<DefaultChangeXMLElementType <NoChangeXMLElementType>>
<DefaultChangeTextVariableInstance <NoChangeTextVariableInstance>>
<DefaultChangeCrossReferenceFormat <NoChangeCrossReferenceFormat>>
<DefaultChangeIndexFormat <NoChangeIndexFormat>>
<DefaultChangeParagraphStyle <NoChangeParagraphStyle>>
<DefaultChangeCharacterStyle <NoChangeCharacterStyle>>
<DefaultChangeTableStyle <NoChangeTableStyle>>
<DefaultChangeCellStyle <NoChangeCellStyle>>
<DefaultChangeObjectStyle <NoChangeObjectStyle>>
<DefaultChangeRootStyle <NoChangeRootStyle>>
<DefaultChangeConditionalTextTag <NoChangeConditionalTextTag>>
<DefaultChangeVariable <NoChangeVariable>>
<DefaultChangeXMLComment <NoChangeXMLComment>>
<DefaultChangeXMLElement <NoChangeXMLElement>>
<DefaultChangeSVVariable <NoChangeSVVariable>>
<DefaultChangeSVVariableInstance <NoChangeSVVariableInstance>>
<DefaultChangeCondition <NoChangeCondition>>
<DefaultChange <NoChange>>
<DefaultChangeList <NoChangeList>>
<DefaultChangePage <NoChangePage>>
<DefaultChangeColumn <NoChangeColumn>>
<DefaultChangeRow <NoChangeRow>>
<DefaultChangeCell <NoChangeCell>>
<DefaultChangeLine <NoChangeLine>>
<DefaultChangeText <NoChangeText>>
<DefaultChangeFrame <NoChangeFrame>>
<DefaultChangeGraphic <NoChangeGraphic>>
<DefaultChangeMarker <NoChangeMarker>>
<DefaultChangeImage <NoChangeImage>>
<DefaultChangeXMLElement <NoChangeXMLElement>>
<DefaultChangeXMLElementType <NoChangeXMLElementType>>
<DefaultChangeTextVariableInstance <NoChangeTextVariableInstance>>
<DefaultChangeCrossReferenceFormat <NoChangeCrossReferenceFormat>>
<DefaultChangeIndexFormat <NoChangeIndexFormat>>
<DefaultChangeParagraphStyle <NoChangeParagraphStyle>>
<DefaultChangeCharacterStyle <NoChangeCharacterStyle>>
<DefaultChangeTableStyle <NoChangeTableStyle>>
<DefaultChangeCellStyle <NoChangeCellStyle>>
<DefaultChangeObjectStyle <NoChangeObjectStyle>>
<DefaultChangeRootStyle <NoChangeRootStyle>>
<DefaultChangeConditionalTextTag <NoChangeConditionalTextTag>>
<DefaultChangeVariable <NoChangeVariable>>
<DefaultChangeXMLComment <NoChangeXMLComment>>
<DefaultChangeXMLElement <NoChangeXMLElement>>
<DefaultChangeSVVariable <NoChangeSVVariable>>
<DefaultChangeSVVariableInstance <NoChangeSVVariableInstance>>
<DefaultChangeCondition <NoChangeCondition>>
>>
"""

# Create the tmp directory if it doesn't exist
os.makedirs('./tmp/', exist_ok=True)

# Save the mif file with the specified content
file_path = './tmp/platform_independent.mif'
with open(file_path, 'w') as f:
    f.write(mif_content)

print(f'MIF file generated: {file_path}')