from PIL import Image, ImageDraw, ImageFont
import random

# Define image dimensions and background color
image_width = 600
image_height = 400
background_color = (220, 220, 220)  # Light gray

# Create a new image with specified background color
image = Image.new('RGB', (image_width, image_height), background_color)
draw = ImageDraw.Draw(image)

# Define a list of texts with varying font sizes and colors
texts = [
    {"text": "Complex File Structure", "font_size": 30, "color": "blue"},
    {"text": "Generated by AI Assistant", "font_size": 20, "color": "green"},
    {"text": "Randomized Font Sizes", "font_size": 25, "color": "red"},
    {"text": "Multiple Lines of Text", "font_size": 18, "color": "purple"}
]

# Load a font
font = ImageFont.load_default()

# Define initial y-coordinate for text
y = 50

# Draw multiple lines of text with varying sizes and colors
for text_data in texts:
    font_size = text_data["font_size"]
    color = text_data["color"]
    
    font = ImageFont.load_default()  # Use a system font

    draw.text((50, y), text_data["text"], fill=color, font=font)
    y += font_size + 10  # Increase y-coordinate for the next line

# Save the image with a complex file structure
image.save('./tmp/complex_structure.jpg')