from moviepy.editor import ColorClip, concatenate_videoclips
from moviepy.video.fx.all import even_size
import os

# Ensure the ./tmp/ directory exists
output_dir = './tmp/'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Create a list of color clips (acting as different parts of the video) with keyframes
# Each color clip will be 2 seconds long
clips = []
# Define colors using RGB tuples
colors = [(255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 0)]  # red, green, blue, yellow
for color in colors:
    clip = ColorClip(size=(640, 480), color=color, duration=2)
    clip = even_size(clip)  # Ensure size is even (required for some codecs)
    clips.append(clip)

# Concatenate the color clips into one video
final_clip = concatenate_videoclips(clips)

# Save the video as an FLV file with keyframes and Script Data Objects
output_file = os.path.join(output_dir, 'example_with_script_data.flv')

# Since MoviePy doesn't natively support adding Script Data Objects directly to FLV files,
# we need to manually add metadata or use an external tool/library to manipulate the FLV container.
# This could involve post-processing the FLV file generated by MoviePy to inject Script Data Objects.

# For demonstration, we'll save the video and print a placeholder message.
# In practice, you would use a tool like ffmpeg or a library that can manipulate FLV containers.
final_clip.write_videofile(output_file, codec='flv', fps=24)

# Placeholder for adding Script Data Objects
# Here you would include the logic or command to add Script Data Objects to the FLV file.
# This step is highly dependent on the tools or libraries available in your environment.
print(f"Video saved to {output_file}")
print("NOTE: This code does not actually add Script Data Objects. You would need to use an external tool or library to add Script Data Objects to the FLV file after it has been created by MoviePy.")